spring:
  application:
    name: store
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 100
  supported-currencies:  USD, TL, EUR
payment-gateway: paypal
mail:
  host: https://crazy.gmail.com
  port: 5761